[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 AppBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 Google FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ Microsoft Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ Microsoft OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ Microsoft Services,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple Services,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🎶 NetEase Music,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 Games,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 Games,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 Games,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 Games,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 Games,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 Bahamut,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 Media CN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 Foreign Media,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 Proxies,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 Direct,[]GEOIP,LAN
ruleset=🎯 Direct,[]GEOIP,CN
ruleset=🐟 Match,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 Proxies`select`[]♻️ Switch`[]🔯 FallBack`[]🔮 LoadBalance`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 US`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch`[]DIRECT
custom_proxy_group=🚀 Switch`select`.*
custom_proxy_group=♻️ URL-Test`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 FallBack`fallback`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 LoadBalance`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 Telegram`select`[]🚀 Proxies`[]♻️ Switch`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch`[]DIRECT
custom_proxy_group=💬 AI`select`[]🚀 Proxies`[]♻️ Switch`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 Proxies`[]♻️ Switch`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🎥 Netflix Unlock`[]🚀 Proxies`[]♻️ Switch`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch`[]DIRECT
custom_proxy_group=📺 Bahamut`select`[]🇹🇼 Taiwan`[]🚀 Proxies`[]🚀 Switch`[]DIRECT
custom_proxy_group=📺 Bilibili`select`[]🎯 Direct`[]🇹🇼 Taiwan`[]🇭🇰 Hong Kong
custom_proxy_group=🌍 Foreign Media`select`[]🚀 Proxies`[]♻️ Switch`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 US`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch`[]DIRECT
custom_proxy_group=🌏 Media CN`select`[]DIRECT`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=📢 Google FCM`select`[]DIRECT`[]🚀 Proxies`[]🇺🇲 US`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=Ⓜ️ Microsoft Bing`select`[]DIRECT`[]🚀 Proxies`[]🇺🇲 US`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=Ⓜ️ Microsoft OneDrive`select`[]DIRECT`[]🚀 Proxies`[]🇺🇲 US`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=Ⓜ️ Microsoft Services`select`[]DIRECT`[]🚀 Proxies`[]🇺🇲 US`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=🍎 Apple Services`select`[]DIRECT`[]🚀 Proxies`[]🇺🇲 US`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=🎮 Games`select`[]DIRECT`[]🚀 Proxies`[]🇺🇲 US`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=🎶 NetEase Music`select`[]DIRECT`[]🚀 Proxies`[]♻️ Switch`(网易|音乐|Music|NetEase)
custom_proxy_group=🎯 Direct`select`[]DIRECT`[]🚀 Proxies`[]♻️ Switch
custom_proxy_group=🛑 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 AppBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 Match`select`[]🚀 Proxies`[]♻️ Switch`[]DIRECT`[]🇭🇰 Hong Kong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 US`[]🇰🇷 Korea`[]🇩🇪 Germany`[]🇦🇹 Austria`[]🇬🇧 GB`[]🇨🇦 Canada`[]🇫🇷 France`[]🇳🇱 Netherland`[]🇦🇺 Australia`[]☁ Cloudflare`[]☁ Cloudflare`[]🚀 Switch
custom_proxy_group=🇭🇰 Hong Kong`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|jp)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 US`url-test`(美|美国|美利坚|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|USA|America)`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇹🇼 Taiwan`url-test`(台|新北|彰化|TW|tw|Taiwan|中华民国|ROC|TaiWan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Singapore`url-test`(新加坡|坡|狮城|SG|Singapore|sg)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 Korea`url-test`(KR|Korea|KOR|首尔|韩|韓|大韩民国)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 Germany`url-test`(德|DE|de|Germany|German|德国|Frankfurt)`http://www.gstatic.com/generate_204`300,,90
custom_proxy_group=🇦🇹 Austria`url-test`(奥|AT|Austria)`http://www.gstatic.com/generate_204`300,,90
custom_proxy_group=🇬🇧 GB`url-test`(英|UK|GB|Britain|United Kingdom|UnitedKingdom|英国)`http://www.gstatic.com/generate_204`300,,90
custom_proxy_group=🇨🇦 Canada`url-test`(CA|Canada|加拿大)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇫🇷 France`url-test`(法|FR|France)`http://www.gstatic.com/generate_204`300,,90
custom_proxy_group=🇳🇱 Netherland`url-test`(荷|NL|Netherlands|Holland|荷兰)`http://www.gstatic.com/generate_204`300,,90
custom_proxy_group=🇦🇺 Australia`url-test`(澳|AU|Australia|澳洲|澳大利亚|大洋洲)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=☁ Cloudflare`select`(CF随机|ProxyIP|优选|Cloudflare|cloudflare|worker|CMLiu|edgetunnel|edtunnel|bpb|甬哥|yongge)`http://www.gstatic.com/generate_204`300,,90
custom_proxy_group=🎥 Netflix Unlock`select`(NF|奈飞|Netflix|NETFLIX|Media|流媒体)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck